# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'acc_info - Copy.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 586)
        font = QFont()
        font.setFamilies([u"Vladimir Script"])
        font.setPointSize(18)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.login_text = QLabel(self.centralwidget)
        self.login_text.setObjectName(u"login_text")
        self.login_text.setGeometry(QRect(70, 0, 491, 111))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush1)
        self.login_text.setPalette(palette)
        font1 = QFont()
        font1.setFamilies([u"Comic Sans MS"])
        font1.setPointSize(48)
        font1.setBold(True)
        font1.setItalic(False)
        self.login_text.setFont(font1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(-120, -50, 981, 661))
        self.label_2.setPixmap(QPixmap(u"../img/1537562.png"))
        self.label_2.setScaledContents(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(60, 390, 111, 51))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_7.setPalette(palette1)
        font2 = QFont()
        font2.setFamilies([u"Comic Sans MS"])
        font2.setPointSize(24)
        self.label_7.setFont(font2)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(60, 160, 121, 51))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_8.setPalette(palette2)
        self.label_8.setFont(font2)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(60, 100, 281, 51))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_10.setPalette(palette3)
        self.label_10.setFont(font2)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(370, 110, 191, 41))
        font3 = QFont()
        font3.setFamilies([u"Comic Sans MS"])
        font3.setPointSize(18)
        self.pushButton.setFont(font3)
        self.name_info = QLabel(self.centralwidget)
        self.name_info.setObjectName(u"name_info")
        self.name_info.setGeometry(QRect(230, 230, 391, 51))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.name_info.setPalette(palette4)
        self.name_info.setFont(font2)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(60, 210, 91, 51))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_13.setPalette(palette5)
        self.label_13.setFont(font2)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(60, 270, 151, 51))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_14.setPalette(palette6)
        self.label_14.setFont(font2)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(60, 330, 151, 51))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_15.setPalette(palette7)
        self.label_15.setFont(font2)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(660, 10, 111, 141))
        self.label.setPixmap(QPixmap(u"../img/costume2.svg"))
        self.label.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_2.raise_()
        self.login_text.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.pushButton.raise_()
        self.name_info.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.login_text.setText(QCoreApplication.translate("MainWindow", u"Account info", None))
        self.label_2.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Name: ", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Profile Picture:", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"<< Upload >>", None))
        self.name_info.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Age:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Weight:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Height:", None))
        self.label.setText("")
    # retranslateUi

