# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'acc_info.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 586)
        font = QFont()
        font.setFamilies([u"Comfortaa"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.login_text = QLabel(self.centralwidget)
        self.login_text.setObjectName(u"login_text")
        self.login_text.setGeometry(QRect(90, 10, 531, 71))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush1)
        self.login_text.setPalette(palette)
        font1 = QFont()
        font1.setFamilies([u"Comfortaa"])
        font1.setPointSize(40)
        font1.setBold(True)
        font1.setItalic(False)
        self.login_text.setFont(font1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(-120, -50, 981, 661))
        self.label_2.setPixmap(QPixmap(u"../img/1537562.png"))
        self.label_2.setScaledContents(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(60, 380, 81, 51))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_7.setPalette(palette1)
        font2 = QFont()
        font2.setFamilies([u"Comfortaa"])
        font2.setPointSize(15)
        self.label_7.setFont(font2)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(60, 130, 91, 51))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_8.setPalette(palette2)
        self.label_8.setFont(font2)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 430, 131, 51))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_9.setPalette(palette3)
        self.label_9.setFont(font2)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(60, 80, 291, 51))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_10.setPalette(palette4)
        self.label_10.setFont(font2)
        self.uploadBtn = QPushButton(self.centralwidget)
        self.uploadBtn.setObjectName(u"uploadBtn")
        self.uploadBtn.setGeometry(QRect(250, 90, 201, 31))
        self.uploadBtn.setFont(font2)
        self.name_info = QLabel(self.centralwidget)
        self.name_info.setObjectName(u"name_info")
        self.name_info.setGeometry(QRect(230, 230, 391, 51))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.name_info.setPalette(palette5)
        font3 = QFont()
        font3.setFamilies([u"Comic Sans MS"])
        font3.setPointSize(24)
        self.name_info.setFont(font3)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(60, 180, 61, 51))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_13.setPalette(palette6)
        self.label_13.setFont(font2)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(60, 280, 101, 51))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_14.setPalette(palette7)
        self.label_14.setFont(font2)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(60, 330, 101, 51))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_15.setPalette(palette8)
        self.label_15.setFont(font2)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(60, 230, 111, 51))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_11.setPalette(palette9)
        self.label_11.setFont(font2)
        self.txtName = QLineEdit(self.centralwidget)
        self.txtName.setObjectName(u"txtName")
        self.txtName.setGeometry(QRect(180, 140, 291, 28))
        self.txtName.setReadOnly(False)
        self.txtAge = QLineEdit(self.centralwidget)
        self.txtAge.setObjectName(u"txtAge")
        self.txtAge.setGeometry(QRect(180, 190, 291, 28))
        self.txtWeight = QLineEdit(self.centralwidget)
        self.txtWeight.setObjectName(u"txtWeight")
        self.txtWeight.setGeometry(QRect(180, 290, 291, 28))
        self.txtHeight = QLineEdit(self.centralwidget)
        self.txtHeight.setObjectName(u"txtHeight")
        self.txtHeight.setGeometry(QRect(180, 340, 291, 28))
        self.txtEmail = QLineEdit(self.centralwidget)
        self.txtEmail.setObjectName(u"txtEmail")
        self.txtEmail.setGeometry(QRect(180, 390, 291, 28))
        self.txtEmail.setReadOnly(True)
        self.txtPassword = QLineEdit(self.centralwidget)
        self.txtPassword.setObjectName(u"txtPassword")
        self.txtPassword.setGeometry(QRect(180, 440, 291, 28))
        self.txtPassword.setReadOnly(True)
        self.btnUpdate = QPushButton(self.centralwidget)
        self.btnUpdate.setObjectName(u"btnUpdate")
        self.btnUpdate.setGeometry(QRect(180, 500, 201, 31))
        self.btnUpdate.setFont(font2)
        self.txtGender = QComboBox(self.centralwidget)
        self.txtGender.addItem("")
        self.txtGender.addItem("")
        self.txtGender.setObjectName(u"txtGender")
        self.txtGender.setGeometry(QRect(180, 240, 131, 28))
        self.avatarLabel = QLabel(self.centralwidget)
        self.avatarLabel.setObjectName(u"avatarLabel")
        self.avatarLabel.setGeometry(QRect(650, 10, 131, 111))
        self.avatarLabel.setScaledContents(True)
        self.btnBack = QPushButton(self.centralwidget)
        self.btnBack.setObjectName(u"btnBack")
        self.btnBack.setGeometry(QRect(540, 500, 201, 31))
        self.btnBack.setFont(font2)
        self.bmi = QLabel(self.centralwidget)
        self.bmi.setObjectName(u"bmi")
        self.bmi.setGeometry(QRect(540, 170, 251, 31))
        self.bmi.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.caculateBtn = QPushButton(self.centralwidget)
        self.caculateBtn.setObjectName(u"caculateBtn")
        self.caculateBtn.setGeometry(QRect(590, 210, 201, 29))
        font4 = QFont()
        font4.setFamilies([u"Segoe UI"])
        font4.setPointSize(15)
        self.caculateBtn.setFont(font4)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(570, 110, 211, 61))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label_12.setPalette(palette10)
        font5 = QFont()
        font5.setFamilies([u"Segoe UI"])
        font5.setPointSize(16)
        self.label_12.setFont(font5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_2.raise_()
        self.login_text.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.uploadBtn.raise_()
        self.name_info.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_11.raise_()
        self.txtName.raise_()
        self.txtAge.raise_()
        self.txtWeight.raise_()
        self.txtHeight.raise_()
        self.txtEmail.raise_()
        self.txtPassword.raise_()
        self.btnUpdate.raise_()
        self.txtGender.raise_()
        self.avatarLabel.raise_()
        self.btnBack.raise_()
        self.bmi.raise_()
        self.caculateBtn.raise_()
        self.label_12.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.login_text.setText(QCoreApplication.translate("MainWindow", u"Account info", None))
        self.label_2.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Name: ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Password: ", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Profile Picture:", None))
        self.uploadBtn.setText(QCoreApplication.translate("MainWindow", u"<< Upload >>", None))
        self.name_info.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Age:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Weight:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Height:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Gender:", None))
        self.btnUpdate.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.txtGender.setItemText(0, QCoreApplication.translate("MainWindow", u"Male", None))
        self.txtGender.setItemText(1, QCoreApplication.translate("MainWindow", u"Female", None))

        self.avatarLabel.setText(QCoreApplication.translate("MainWindow", u"Avatar", None))
        self.btnBack.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.bmi.setText("")
        self.caculateBtn.setText(QCoreApplication.translate("MainWindow", u"Caculate Bmi", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Healthcondition:", None))
    # retranslateUi

