# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'food_item.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QListView, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(600, 720)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 380, 31, 31))
        self.label_5.setPixmap(QPixmap(u"../img/notes-medical-solid.svg"))
        self.label_5.setScaledContents(True)
        self.homeBtn = QPushButton(self.centralwidget)
        self.homeBtn.setObjectName(u"homeBtn")
        self.homeBtn.setGeometry(QRect(460, 30, 90, 41))
        self.homeBtn.setAutoFillBackground(False)
        self.homeBtn.setStyleSheet(u"border-radius: 15px")
        icon = QIcon()
        icon.addFile(u"../img/house-chimney-solid.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setIconSize(QSize(40, 40))
        self.image = QLabel(self.centralwidget)
        self.image.setObjectName(u"image")
        self.image.setGeometry(QRect(0, 0, 601, 351))
        self.image.setPixmap(QPixmap(u"../img/Carrot-Cake-Recipe-Video.jpg"))
        self.image.setScaledContents(True)
        self.money = QLabel(self.centralwidget)
        self.money.setObjectName(u"money")
        self.money.setGeometry(QRect(520, 330, 161, 31))
        font = QFont()
        font.setPointSize(11)
        self.money.setFont(font)
        self.like = QLabel(self.centralwidget)
        self.like.setObjectName(u"like")
        self.like.setGeometry(QRect(520, 380, 161, 31))
        self.like.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 330, 31, 31))
        self.label_3.setPixmap(QPixmap(u"../img/clock-regular.svg"))
        self.label_3.setScaledContents(True)
        self.healthy = QLabel(self.centralwidget)
        self.healthy.setObjectName(u"healthy")
        self.healthy.setGeometry(QRect(40, 380, 161, 31))
        self.healthy.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(160, 330, 31, 31))
        self.label_4.setPixmap(QPixmap(u"../img/leaf-solid.svg"))
        self.label_4.setScaledContents(True)
        self.classify = QLabel(self.centralwidget)
        self.classify.setObjectName(u"classify")
        self.classify.setGeometry(QRect(10, 30, 91, 25))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.classify.setFont(font1)
        self.classify.setStyleSheet(u"background-color: rgb(255, 255, 255); \n"
"border-radius: 10px")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(490, 330, 21, 31))
        self.label_7.setPixmap(QPixmap(u"../img/dollar-sign-solid.svg"))
        self.label_7.setScaledContents(True)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 380, 31, 31))
        self.label_6.setPixmap(QPixmap(u"../img/person-solid.svg"))
        self.label_6.setScaledContents(True)
        self.time = QLabel(self.centralwidget)
        self.time.setObjectName(u"time")
        self.time.setGeometry(QRect(40, 330, 161, 31))
        self.time.setFont(font)
        self.name = QLabel(self.centralwidget)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(180, 260, 251, 91))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        self.name.setFont(font2)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(480, 380, 31, 31))
        self.label_8.setPixmap(QPixmap(u"../img/heart-regular.svg"))
        self.label_8.setScaledContents(True)
        self.popular = QLabel(self.centralwidget)
        self.popular.setObjectName(u"popular")
        self.popular.setGeometry(QRect(200, 380, 161, 31))
        self.popular.setFont(font)
        self.vegetarian = QLabel(self.centralwidget)
        self.vegetarian.setObjectName(u"vegetarian")
        self.vegetarian.setGeometry(QRect(200, 330, 161, 31))
        self.vegetarian.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 320, 611, 551))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.dairy = QLabel(self.centralwidget)
        self.dairy.setObjectName(u"dairy")
        self.dairy.setGeometry(QRect(360, 380, 161, 31))
        self.dairy.setFont(font)
        self.gluten = QLabel(self.centralwidget)
        self.gluten.setObjectName(u"gluten")
        self.gluten.setGeometry(QRect(360, 330, 161, 31))
        self.gluten.setFont(font)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(320, 380, 31, 31))
        self.label_10.setPixmap(QPixmap(u"../img/cow-solid.svg"))
        self.label_10.setScaledContents(True)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(320, 330, 31, 31))
        self.label_11.setPixmap(QPixmap(u"../img/wheat-awn-circle-exclamation-solid.svg"))
        self.label_11.setScaledContents(True)
        self.name_2 = QLabel(self.centralwidget)
        self.name_2.setObjectName(u"name_2")
        self.name_2.setGeometry(QRect(0, 390, 251, 91))
        self.name_2.setFont(font2)
        self.listView = QListView(self.centralwidget)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(0, 460, 601, 71))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 540, 601, 181))
        font3 = QFont()
        font3.setPointSize(10)
        self.label_2.setFont(font3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.image.raise_()
        self.label.raise_()
        self.dairy.raise_()
        self.name_2.raise_()
        self.time.raise_()
        self.label_5.raise_()
        self.homeBtn.raise_()
        self.money.raise_()
        self.like.raise_()
        self.label_3.raise_()
        self.healthy.raise_()
        self.label_4.raise_()
        self.classify.raise_()
        self.label_6.raise_()
        self.name.raise_()
        self.label_8.raise_()
        self.popular.raise_()
        self.vegetarian.raise_()
        self.gluten.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.listView.raise_()
        self.label_2.raise_()
        self.label_7.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_5.setText("")
        self.homeBtn.setText("")
        self.image.setText("")
        self.money.setText(QCoreApplication.translate("MainWindow", u"cheap", None))
        self.like.setText(QCoreApplication.translate("MainWindow", u"16408", None))
        self.label_3.setText("")
        self.healthy.setText(QCoreApplication.translate("MainWindow", u"healthy", None))
        self.label_4.setText("")
        self.classify.setText(QCoreApplication.translate("MainWindow", u"   SWEET", None))
        self.label_7.setText("")
        self.label_6.setText("")
        self.time.setText(QCoreApplication.translate("MainWindow", u"100min", None))
        self.name.setText(QCoreApplication.translate("MainWindow", u"Carrot cake", None))
        self.label_8.setText("")
        self.popular.setText(QCoreApplication.translate("MainWindow", u"popular", None))
        self.vegetarian.setText(QCoreApplication.translate("MainWindow", u"vegetarian", None))
        self.label.setText("")
        self.dairy.setText(QCoreApplication.translate("MainWindow", u"dairyfree", None))
        self.gluten.setText(QCoreApplication.translate("MainWindow", u"glutenfree", None))
        self.label_10.setText("")
        self.label_11.setText("")
        self.name_2.setText(QCoreApplication.translate("MainWindow", u"Ingredients", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
    # retranslateUi

