# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'home.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(600, 720)
        self.avatar = QLabel(Widget)
        self.avatar.setObjectName(u"avatar")
        self.avatar.setGeometry(QRect(20, 0, 71, 41))
        self.avatar.setPixmap(QPixmap(u"../img/download (2).png"))
        self.avatar.setScaledContents(True)
        self.username = QLabel(Widget)
        self.username.setObjectName(u"username")
        self.username.setGeometry(QRect(-10, 0, 641, 841))
        font = QFont()
        font.setBold(True)
        self.username.setFont(font)
        self.username.setStyleSheet(u"border-radius: 20px;\n"
"background: rgb(255, 255, 255)")
        self.Hello = QLabel(Widget)
        self.Hello.setObjectName(u"Hello")
        self.Hello.setGeometry(QRect(90, 10, 21, 21))
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 50, 161, 41))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.label.setFont(font1)
        self.hello = QLabel(Widget)
        self.hello.setObjectName(u"hello")
        self.hello.setGeometry(QRect(30, 90, 851, 20))
        self.allFood = QPushButton(Widget)
        self.allFood.setObjectName(u"allFood")
        self.allFood.setGeometry(QRect(40, 120, 55, 55))
        self.allFood.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 170, 127);")
        self.veganFood = QPushButton(Widget)
        self.veganFood.setObjectName(u"veganFood")
        self.veganFood.setGeometry(QRect(150, 120, 55, 55))
        self.veganFood.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(85, 255, 127)")
        self.waterFood = QPushButton(Widget)
        self.waterFood.setObjectName(u"waterFood")
        self.waterFood.setGeometry(QRect(260, 120, 55, 55))
        self.waterFood.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(0, 170, 255)")
        self.meatFood = QPushButton(Widget)
        self.meatFood.setObjectName(u"meatFood")
        self.meatFood.setGeometry(QRect(370, 120, 55, 55))
        self.meatFood.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(170, 85, 255)")
        self.sweetFood = QPushButton(Widget)
        self.sweetFood.setObjectName(u"sweetFood")
        self.sweetFood.setGeometry(QRect(480, 120, 55, 55))
        self.sweetFood.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 85, 0)")
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 120, 55, 55))
        self.label_3.setPixmap(QPixmap(u"../img/download (9).png"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 120, 55, 55))
        self.label_4.setPixmap(QPixmap(u"../img/download (15).png"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(370, 120, 55, 55))
        self.label_5.setPixmap(QPixmap(u"../img/download (11).png"))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(260, 120, 55, 55))
        self.label_6.setPixmap(QPixmap(u"../img/download (12).png"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(480, 120, 55, 55))
        self.label_7.setPixmap(QPixmap(u"../img/download (14).png"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(50, 180, 55, 20))
        self.label_8.setFont(font)
        self.label_9 = QLabel(Widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(150, 180, 55, 20))
        self.label_9.setFont(font)
        self.label_10 = QLabel(Widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(260, 180, 55, 20))
        self.label_10.setFont(font)
        self.label_11 = QLabel(Widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(370, 180, 55, 20))
        self.label_11.setFont(font)
        self.label_12 = QLabel(Widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(480, 180, 57, 20))
        self.label_12.setFont(font)
        self.search = QLineEdit(Widget)
        self.search.setObjectName(u"search")
        self.search.setGeometry(QRect(340, 10, 191, 26))
        self.search.setStyleSheet(u"border-radius: 10px;\n"
"background-color: rgb(189, 189, 189);")
        self.hi = QLabel(Widget)
        self.hi.setObjectName(u"hi")
        self.hi.setGeometry(QRect(110, 10, 221, 21))
        self.searchBtn = QPushButton(Widget)
        self.searchBtn.setObjectName(u"searchBtn")
        self.searchBtn.setGeometry(QRect(530, 10, 41, 29))
        self.searchBtn.setAutoFillBackground(True)
        icon = QIcon()
        icon.addFile(u"../img/magnifying-glass-solid.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.searchBtn.setIcon(icon)
        self.searchBtn.setIconSize(QSize(25, 25))
        self.listItems = QWidget(Widget)
        self.listItems.setObjectName(u"listItems")
        self.listItems.setGeometry(QRect(40, 210, 500, 500))
        self.username.raise_()
        self.avatar.raise_()
        self.Hello.raise_()
        self.label.raise_()
        self.hello.raise_()
        self.allFood.raise_()
        self.veganFood.raise_()
        self.waterFood.raise_()
        self.meatFood.raise_()
        self.sweetFood.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.hi.raise_()
        self.listItems.raise_()
        self.search.raise_()
        self.searchBtn.raise_()

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.avatar.setText("")
        self.username.setText("")
        self.Hello.setText(QCoreApplication.translate("Widget", u"Hi, 12345", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Categories", None))
        self.hello.setText(QCoreApplication.translate("Widget", u"Quick and delicious", None))
        self.allFood.setText("")
        self.veganFood.setText("")
        self.waterFood.setText("")
        self.meatFood.setText("")
        self.sweetFood.setText("")
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText(QCoreApplication.translate("Widget", u"ALL", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"VEGAN", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"WATER", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"MEAT", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"SWEET", None))
        self.search.setText(QCoreApplication.translate("Widget", u"Search", None))
        self.hi.setText(QCoreApplication.translate("Widget", u"12345", None))
        self.searchBtn.setText("")
    # retranslateUi

