# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'register.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(420, 650)
        font = QFont()
        font.setFamilies([u"Vladimir Script"])
        font.setPointSize(18)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.register_text = QLabel(self.centralwidget)
        self.register_text.setObjectName(u"register_text")
        self.register_text.setGeometry(QRect(40, 140, 331, 111))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush1)
        self.register_text.setPalette(palette)
        font1 = QFont()
        font1.setFamilies([u"Comfortaa"])
        font1.setPointSize(48)
        font1.setBold(True)
        font1.setItalic(False)
        self.register_text.setFont(font1)
        self.txtEmail = QLineEdit(self.centralwidget)
        self.txtEmail.setObjectName(u"txtEmail")
        self.txtEmail.setGeometry(QRect(20, 310, 381, 41))
        palette1 = QPalette()
        brush2 = QBrush(QColor(214, 172, 73, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        self.txtEmail.setPalette(palette1)
        font2 = QFont()
        font2.setFamilies([u"Comfortaa"])
        font2.setPointSize(18)
        self.txtEmail.setFont(font2)
        self.txtPassword = QLineEdit(self.centralwidget)
        self.txtPassword.setObjectName(u"txtPassword")
        self.txtPassword.setGeometry(QRect(20, 370, 381, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        self.txtPassword.setPalette(palette2)
        self.txtPassword.setFont(font2)
        self.txtPassword.setEchoMode(QLineEdit.Password)
        self.btnRegister = QPushButton(self.centralwidget)
        self.btnRegister.setObjectName(u"btnRegister")
        self.btnRegister.setGeometry(QRect(110, 490, 201, 41))
        palette3 = QPalette()
        brush3 = QBrush(QColor(159, 159, 159, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        self.btnRegister.setPalette(palette3)
        self.btnRegister.setFont(font2)
        self.btnRegister_2 = QPushButton(self.centralwidget)
        self.btnRegister_2.setObjectName(u"btnRegister_2")
        self.btnRegister_2.setGeometry(QRect(90, 560, 261, 21))
        palette4 = QPalette()
        brush4 = QBrush(QColor(0, 0, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush4)
        brush5 = QBrush(QColor(255, 0, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        self.btnRegister_2.setPalette(palette4)
        font3 = QFont()
        font3.setFamilies([u"Comfortaa"])
        font3.setPointSize(10)
        self.btnRegister_2.setFont(font3)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, -40, 441, 661))
        self.label_2.setPixmap(QPixmap(u"../img/fa610763f8007b711ec710aef08b0e15.jpg"))
        self.label_2.setScaledContents(True)
        self.txtCPassword = QLineEdit(self.centralwidget)
        self.txtCPassword.setObjectName(u"txtCPassword")
        self.txtCPassword.setGeometry(QRect(20, 430, 381, 41))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        self.txtCPassword.setPalette(palette5)
        self.txtCPassword.setFont(font2)
        self.txtCPassword.setEchoMode(QLineEdit.Password)
        self.txtName = QLineEdit(self.centralwidget)
        self.txtName.setObjectName(u"txtName")
        self.txtName.setGeometry(QRect(20, 250, 381, 41))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        self.txtName.setPalette(palette6)
        self.txtName.setFont(font2)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 421, 101))
        self.label_3.setPixmap(QPixmap(u"../../../../Desktop/ClassIn_20240714150608.jpg"))
        self.label_3.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_2.raise_()
        self.btnRegister.raise_()
        self.btnRegister_2.raise_()
        self.register_text.raise_()
        self.txtEmail.raise_()
        self.txtPassword.raise_()
        self.txtCPassword.raise_()
        self.txtName.raise_()
        self.label_3.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.register_text.setText(QCoreApplication.translate("MainWindow", u"Register", None))
        self.txtEmail.setText("")
        self.txtEmail.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.txtPassword.setText("")
        self.txtPassword.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.btnRegister.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.btnRegister_2.setText(QCoreApplication.translate("MainWindow", u"Already have an account?", None))
        self.label_2.setText("")
        self.txtCPassword.setText("")
        self.txtCPassword.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Confirm password", None))
        self.txtName.setText("")
        self.txtName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Username", None))
        self.label_3.setText("")
    # retranslateUi

